use super::KeywordKind;

pub(crate) const UTF8_1_BYTE_MASK: u8 = 0b1000_0000;
pub(crate) const UTF8_1_BYTE_PATTERN: u8 = 0b0000_0000;
pub(crate) const UTF8_2_BYTE_MASK: u8 = 0b1110_0000;
pub(crate) const UTF8_2_BYTE_PATTERN: u8 = 0b1100_0000;
pub(crate) const UTF8_3_BYTE_MASK: u8 = 0b1111_0000;
pub(crate) const UTF8_3_BYTE_PATTERN: u8 = 0b1110_0000;
pub(crate) const UTF8_4_BYTE_MASK: u8 = 0b1111_1000;
pub(crate) const UTF8_4_BYTE_PATTERN: u8 = 0b1111_0000;
pub(crate) const AVG_BYTES_PER_TOKEN: usize = 5;
pub(crate) const MULTI_LINE_STRING_SEQUENCES: &[&[u8]] = &[b"```", b"~~~"];
pub(crate) const BOOL_LITERALS: &[&[u8]] =
    &[b"true", b"false", b"True", b"False", b"TRUE", b"FALSE"];
pub(crate) const TIMESPAN_SUFFIXES: &[&[u8]] = &[
    b"microseconds",
    b"milliseconds",
    b"nanoseconds",
    b"microsecond",
    b"millisecond",
    b"nanosecond",
    b"microsec",
    b"millisec",
    b"nanosec",
    b"minutes",
    b"seconds",
    b"hours",
    b"micros",
    b"millis",
    b"nanos",
    b"minute",
    b"second",
    b"hour",
    b"micro",
    b"milli",
    b"nano",
    b"ticks",
    b"tick",
    b"hrs",
    b"sec",
    b"min",
    b"day",
    b"ms",
    b"hr",
    b"d",
    b"h",
    b"m",
    b"s",
];
pub(crate) const KEYWORDS: &[(&[u8], KeywordKind)] = &[
    (
        b"storedqueryresultcontainers",
        KeywordKind::StoredQueryResultContainers,
    ),
    (
        b"materialized-view-combine",
        KeywordKind::MaterializedViewCombine,
    ),
    (b"__contextual_datatable", KeywordKind::ContextualDataTable),
    (b"restricted_view_access", KeywordKind::RestrictedViewAccess),
    (b"extent_tags_retention", KeywordKind::ExtentTagsRetention),
    (b"inline_external_table", KeywordKind::InlineExternalTable),
    (b"graph-mark-components", KeywordKind::GraphMarkComponents),
    (b"commands-and-queries", KeywordKind::CommandsAndQueries),
    (b"graph-shortest-paths", KeywordKind::GraphShortestPaths),
    (b"hint.progressive_top", KeywordKind::HintDotProgressiveTop),
    (b"__sourceColumnIndex", KeywordKind::__SourceColumnIndex),
    (b"hint.num_partitions", KeywordKind::HintDotNumPartitions),
    (b"rowstore_references", KeywordKind::RowstoreReferences),
    (b"unrestrictedviewers", KeywordKind::UnrestrictedViewers),
    (b"materialized-views", KeywordKind::MaterializedViews),
    (b"row_level_security", KeywordKind::RowLevelSecurity),
    (b"__executeAndCache", KeywordKind::ExecuteAndCache),
    (b"hint.distribution", KeywordKind::HintDotDistribution),
    (b"hint.materialized", KeywordKind::HintDotMaterialized),
    (b"graph-where-nodes", KeywordKind::GraphWhereNodes),
    (b"graph-where-edges", KeywordKind::GraphWhereEdges),
    (b"rowstore_sealinfo", KeywordKind::RowstoreSealInfo),
    (b"datetime_pattern", KeywordKind::DateTimePattern),
    (b"project-by-names", KeywordKind::ProjectByNames),
    (b"query_parameters", KeywordKind::QueryParameters),
    (b"stackedareachart", KeywordKind::StackedAreaChart),
    (b"hint.concurrency", KeywordKind::HintDotConcurrency),
    (b"hint.shufflekey", KeywordKind::HintDotShuffleKey),
    (b"sample-distinct", KeywordKind::SampleDistinct),
    (b"project-reorder", KeywordKind::ProjectReorder),
    (b"__crossCluster", KeywordKind::__CrossCluster),
    (b"__noWithSource", KeywordKind::__NoWithSource),
    (b"__packedColumn", KeywordKind::__PackedColumn),
    (b"rowstorepolicy", KeywordKind::RowstorePolicy),
    (b"encodingpolicy", KeywordKind::EncodingPolicy),
    (b"graph-to-table", KeywordKind::GraphToTable),
    (b"nooptimization", KeywordKind::NoOptimization),
    (b"partitioned-by", KeywordKind::PartitionedBy),
    (b"project-rename", KeywordKind::ProjectRename),
    (b"with_itemindex", KeywordKind::WithItemIndex),
    (b"with_step_name", KeywordKind::WithStepName),
    (b"!startswith_cs", KeywordKind::NotStartsWithCs),
    (b"set-or-replace", KeywordKind::SetOrReplace),
    (b"assert-schema", KeywordKind::AssertSchema),
    (b"cachingpolicy", KeywordKind::CachingPolicy),
    (b"external_data", KeywordKind::ExternalData2),
    (b"hardretention", KeywordKind::HardRetention),
    (b"hint.strategy", KeywordKind::HintDotStrategy),
    (b"matches regex", KeywordKind::MatchesRegex),
    (b"notcontainscs", KeywordKind::NotContainsCs),
    (b"!hasprefix_cs", KeywordKind::NotHasPrefixCs),
    (b"!hassuffix_cs", KeywordKind::NotHasSuffixCs),
    (b"__partitionby", KeywordKind::PartitionBy),
    (b"__projectAway", KeywordKind::_ProjectAway),
    (b"project-smart", KeywordKind::ProjectSmart),
    (b"query_results", KeywordKind::QueryResults),
    (b"set-or-append", KeywordKind::SetOrAppend),
    (b"softretention", KeywordKind::SoftRetention),
    (b"startswith_cs", KeywordKind::StartsWithCs),
    (b"writeaheadlog", KeywordKind::WriteAheadLog),
    (b"with_match_id", KeywordKind::WithMatchId),
    (b"anomalychart", KeywordKind::AnomalyChart),
    (b"bagexpansion", KeywordKind::BagExpansion),
    (b"decodeblocks", KeywordKind::DecodeBlocks),
    (b"entity_group", KeywordKind::EntityGroup),
    (b"externaldata", KeywordKind::ExternalData),
    (b"expandoutput", KeywordKind::ExpandOutput),
    (b"force_remote", KeywordKind::ForceRemote),
    (b"hasprefix_cs", KeywordKind::HasPrefixCs),
    (b"hassuffix_cs", KeywordKind::HasSuffixCs),
    (b"macro-expand", KeywordKind::MacroExpand),
    (b"project-away", KeywordKind::ProjectAway),
    (b"scatterchart", KeywordKind::ScatterChart),
    (b"!contains_cs", KeywordKind::NotBangContainsCs),
    (b"!endswith_cs", KeywordKind::NotEndsWithCs),
    (b"with_node_id", KeywordKind::WithNodeId),
    (b"project-keep", KeywordKind::ProjectKeep),
    (b"columnchart", KeywordKind::ColumnChart),
    (b"contains_cs", KeywordKind::ContainsCs2),
    (b"endswith_cs", KeywordKind::EndsWithCs),
    (b"granny-desc", KeywordKind::GrannyDesc),
    (b"graph-match", KeywordKind::GraphMatch),
    (b"best_effort", KeywordKind::BestEffort),
    (b"ladderchart", KeywordKind::LadderChart),
    (b"make-series", KeywordKind::MakeSeries),
    (b"materialize", KeywordKind::Materialize),
    (b"notcontains", KeywordKind::NotContains),
    (b"!startswith", KeywordKind::NotStartsWith),
    (b"parse-where", KeywordKind::ParseWhere),
    (b"hint.remote", KeywordKind::HintDotRemote),
    (b"hint.spread", KeywordKind::HintDotSpread),
    (b"top-hitters", KeywordKind::TopHitters),
    (b"with_source", KeywordKind::WithSource),
    (b"accumulate", KeywordKind::Accumulate),
    (b"bin_legacy", KeywordKind::BinLegacy),
    (b"containscs", KeywordKind::ContainsCs),
    (b"dataexport", KeywordKind::DataExport),
    (b"granny-asc", KeywordKind::GrannyAsc),
    (b"harddelete", KeywordKind::HardDelete),
    (b"!hasprefix", KeywordKind::NotHasPrefix),
    (b"!hassuffix", KeywordKind::NotHasSuffix),
    (b"make-graph", KeywordKind::MakeGraph),
    (b"pathformat", KeywordKind::PathFormat),
    (b"pivotchart", KeywordKind::PivotChart),
    (b"softdelete", KeywordKind::SoftDelete),
    (b"startswith", KeywordKind::StartsWith),
    (b"dataformat", KeywordKind::DataFormat),
    (b"statistics", KeywordKind::Statistics),
    (b"tablepurge", KeywordKind::TablePurge),
    (b"top-nested", KeywordKind::TopNested),
    (b"withsource", KeywordKind::WithSource2),
    (b"__crossDB", KeywordKind::__CrossDB),
    (b"__isFuzzy", KeywordKind::__IsFuzzy),
    (b"areachart", KeywordKind::AreaChart),
    (b"datascope", KeywordKind::DataScope),
    (b"datatable", KeywordKind::DataTable),
    (b"getschema", KeywordKind::GetSchema),
    (b"hasprefix", KeywordKind::HasPrefix),
    (b"hassuffix", KeywordKind::HasSuffix),
    (b"linechart", KeywordKind::LineChart),
    (b"mv-expand", KeywordKind::MvDashExpand),
    (b"notlikecs", KeywordKind::NotLikeCs),
    (b"partition", KeywordKind::Partition),
    (b"rowstores", KeywordKind::Rowstores),
    (b"serialize", KeywordKind::Serialize),
    (b"summarize", KeywordKind::Summarize),
    (b"timechart", KeywordKind::TimeChart),
    (b"timepivot", KeywordKind::TimePivot),
    (b"!contains", KeywordKind::NotBangContains),
    (b"!endswith", KeywordKind::NotEndsWith),
    (b"barchart", KeywordKind::BarChart),
    (b"contains", KeywordKind::Contains),
    (b"database", KeywordKind::Database),
    (b"distinct", KeywordKind::Distinct),
    (b"earliest", KeywordKind::Earliest),
    (b"endswith", KeywordKind::EndsWith),
    (b"evaluate", KeywordKind::Evaluate),
    (b"hotcache", KeywordKind::HotCache),
    (b"mv-apply", KeywordKind::MvDashApply),
    (b"mvexpand", KeywordKind::MvExpand),
    (b"parse-kv", KeywordKind::ParseKv),
    (b"piechart", KeywordKind::PieChart),
    (b"restrict", KeywordKind::Restrict),
    (b"rowstore", KeywordKind::Rowstore),
    (b"timeline", KeywordKind::Timeline),
    (b"toscalar", KeywordKind::ToScalar),
    (b"datetime", KeywordKind::DateTime),
    (b"timespan", KeywordKind::Timespan),
    (b"uniqueid", KeywordKind::UniqueId),
    (b"3Dchart", KeywordKind::_3DChart),
    (b"between", KeywordKind::Between),
    (b"callout", KeywordKind::Callout),
    (b"consume", KeywordKind::Consume),
    (b"declare", KeywordKind::Declare),
    (b"default", KeywordKind::Default),
    (b"has_any", KeywordKind::HasAny),
    (b"has_all", KeywordKind::HasAll),
    (b"isfuzzy", KeywordKind::IsFuzzy),
    (b"journal", KeywordKind::Journal),
    (b"missing", KeywordKind::Missing),
    (b"mvapply", KeywordKind::MvApply),
    (b"notlike", KeywordKind::NotLike),
    (b"pattern", KeywordKind::Pattern),
    (b"project", KeywordKind::Project),
    (b"queries", KeywordKind::Queries),
    (b"relaxed", KeywordKind::Relaxed),
    (b"totable", KeywordKind::ToTable),
    (b"treemap", KeywordKind::TreeMap),
    (b"boolean", KeywordKind::Boolean),
    (b"decimal", KeywordKind::Decimal),
    (b"dynamic", KeywordKind::Dynamic),
    (b"verbose", KeywordKind::Verbose),
    (b"plotly", KeywordKind::Plotly),
    (b"access", KeywordKind::Access),
    (b"cancel", KeywordKind::Cancel),
    (b"cycles", KeywordKind::Cycles),
    (b"extend", KeywordKind::Extend),
    (b"filter", KeywordKind::Filter),
    (b"has_cs", KeywordKind::HasCs),
    (b"invoke", KeywordKind::Invoke),
    (b"latest", KeywordKind::Latest),
    (b"likecs", KeywordKind::LikeCs),
    (b"lookup", KeywordKind::Lookup),
    (b"others", KeywordKind::Others),
    (b"output", KeywordKind::Output),
    (b"reduce", KeywordKind::Reduce),
    (b"render", KeywordKind::Render),
    (b"sample", KeywordKind::Sample),
    (b"search", KeywordKind::Search),
    (b"shards", KeywordKind::Shards),
    (b"simple", KeywordKind::Simple),
    (b"typeof", KeywordKind::TypeOf),
    (b"double", KeywordKind::Double),
    (b"string", KeywordKind::String),
    (b"uint16", KeywordKind::UInt16),
    (b"uint32", KeywordKind::UInt32),
    (b"uint64", KeywordKind::UInt64),
    (b"alias", KeywordKind::Alias),
    (b"count", KeywordKind::Count),
    (b"edges", KeywordKind::GraphEdges),
    (b"facet", KeywordKind::Facet),
    (b"first", KeywordKind::First),
    (b"flags", KeywordKind::Flags),
    (b"graph", KeywordKind::Graph),
    (b"limit", KeywordKind::Limit),
    (b"nodes", KeywordKind::Nodes),
    (b"nulls", KeywordKind::Nulls),
    (b"order", KeywordKind::Order),
    (b"parse", KeywordKind::Parse),
    (b"range", KeywordKind::Range),
    (b"regex", KeywordKind::Regex),
    (b"seals", KeywordKind::Seals),
    (b"title", KeywordKind::Title),
    (b"union", KeywordKind::Union),
    (b"views", KeywordKind::Views),
    (b"where", KeywordKind::Where),
    (b"float", KeywordKind::Float),
    (b"int16", KeywordKind::Int16),
    (b"int32", KeywordKind::Int32),
    (b"int64", KeywordKind::Int64),
    (b"uint8", KeywordKind::UInt8),
    (b"ulong", KeywordKind::ULong),
    (b"card", KeywordKind::Card),
    (b"desc", KeywordKind::Desc),
    (b"find", KeywordKind::Find),
    (b"fork", KeywordKind::Fork),
    (b"from", KeywordKind::From),
    (b"join", KeywordKind::Join),
    (b"kind", KeywordKind::Kind),
    (b"last", KeywordKind::Last),
    (b"like", KeywordKind::Like),
    (b"null", KeywordKind::Null),
    (b"pack", KeywordKind::Pack),
    (b"scan", KeywordKind::Scan),
    (b"sort", KeywordKind::Sort),
    (b"step", KeywordKind::Step),
    (b"take", KeywordKind::Take),
    (b"view", KeywordKind::View),
    (b"bool", KeywordKind::Bool),
    (b"byte", KeywordKind::Byte),
    (b"char", KeywordKind::Char),
    (b"date", KeywordKind::Date),
    (b"guid", KeywordKind::Guid),
    (b"int8", KeywordKind::Int8),
    (b"long", KeywordKind::Long),
    (b"real", KeywordKind::Real),
    (b"time", KeywordKind::Time),
    (b"uint", KeywordKind::UInt),
    (b"!has", KeywordKind::NotHas),
    (b"!in~", KeywordKind::NotInCs),
    (b"seal", KeywordKind::Seal),
    (b"__id", KeywordKind::__Id),
    (b"and", KeywordKind::And),
    (b"asc", KeywordKind::Asc),
    (b"bin", KeywordKind::Bin),
    (b"has", KeywordKind::Has),
    (b"in~", KeywordKind::InCs),
    (b"let", KeywordKind::Let),
    (b"mdm", KeywordKind::Mdm),
    (b"set", KeywordKind::Set),
    (b"sql", KeywordKind::Sql),
    (b"top", KeywordKind::Top),
    (b"int", KeywordKind::Int),
    (b"!in", KeywordKind::NotIn),
    (b"as", KeywordKind::As),
    (b"by", KeywordKind::By),
    (b"id", KeywordKind::Id),
    (b"in", KeywordKind::In),
    (b"of", KeywordKind::Of),
    (b"on", KeywordKind::On),
    (b"or", KeywordKind::Or),
    (b"to", KeywordKind::To),
];
