use super::SyntaxKind;

pub(crate) const AVG_BYTES_PER_TOKEN: usize = 5;
pub(crate) const MULTI_LINE_STRING_SEQUENCES: &[&[u8]] = &[b"```", b"~~~"];
pub(crate) const BOOL_LITERALS: &[&[u8]] =
    &[b"true", b"false", b"True", b"False", b"TRUE", b"FALSE"];
pub(crate) const TIMESPAN_SUFFIXES: &[&[u8]] = &[
    b"microseconds",
    b"milliseconds",
    b"nanoseconds",
    b"microsecond",
    b"millisecond",
    b"nanosecond",
    b"microsec",
    b"millisec",
    b"nanosec",
    b"minutes",
    b"seconds",
    b"hours",
    b"micros",
    b"millis",
    b"nanos",
    b"minute",
    b"second",
    b"hour",
    b"micro",
    b"milli",
    b"nano",
    b"ticks",
    b"tick",
    b"hrs",
    b"sec",
    b"min",
    b"day",
    b"ms",
    b"hr",
    b"d",
    b"h",
    b"m",
    b"s",
];
pub(crate) const KEYWORDS: &[(&[u8], SyntaxKind)] = &[
    (
        b"storedqueryresultcontainers",
        SyntaxKind::StoredQueryResultContainersKeyword,
    ),
    (
        b"materialized-view-combine",
        SyntaxKind::MaterializedViewCombineKeyword,
    ),
    (
        b"__contextual_datatable",
        SyntaxKind::ContextualDataTableKeyword,
    ),
    (
        b"restricted_view_access",
        SyntaxKind::RestrictedViewAccessKeyword,
    ),
    (
        b"extent_tags_retention",
        SyntaxKind::ExtentTagsRetentionKeyword,
    ),
    (
        b"inline_external_table",
        SyntaxKind::InlineExternalTableKeyword,
    ),
    (
        b"graph-mark-components",
        SyntaxKind::GraphMarkComponentsKeyword,
    ),
    (
        b"commands-and-queries",
        SyntaxKind::CommandsAndQueriesKeyword,
    ),
    (
        b"graph-shortest-paths",
        SyntaxKind::GraphShortestPathsKeyword,
    ),
    (
        b"hint.progressive_top",
        SyntaxKind::HintDotProgressiveTopKeyword,
    ),
    (
        b"__sourceColumnIndex",
        SyntaxKind::__SourceColumnIndexKeyword,
    ),
    (b"hint.num_partitions", SyntaxKind::HintDotNumPartitions),
    (
        b"rowstore_references",
        SyntaxKind::RowstoreReferencesKeyword,
    ),
    (
        b"unrestrictedviewers",
        SyntaxKind::UnrestrictedViewersKeyword,
    ),
    (b"materialized-views", SyntaxKind::MaterializedViewsKeyword),
    (b"row_level_security", SyntaxKind::RowLevelSecurityKeyword),
    (b"__executeAndCache", SyntaxKind::ExecuteAndCacheKeyword),
    (b"hint.distribution", SyntaxKind::HintDotDistributionKeyword),
    (b"hint.materialized", SyntaxKind::HintDotMaterializedKeyword),
    (b"graph-where-nodes", SyntaxKind::GraphWhereNodesKeyword),
    (b"graph-where-edges", SyntaxKind::GraphWhereEdgesKeyword),
    (b"rowstore_sealinfo", SyntaxKind::RowstoreSealInfoKeyword),
    (b"datetime_pattern", SyntaxKind::DateTimePatternKeyword),
    (b"project-by-names", SyntaxKind::ProjectByNamesKeyword),
    (b"query_parameters", SyntaxKind::QueryParametersKeyword),
    (b"stackedareachart", SyntaxKind::StackedAreaChartKeyword),
    (b"hint.concurrency", SyntaxKind::HintDotConcurrencyKeyword),
    (b"hint.shufflekey", SyntaxKind::HintDotShuffleKeyKeyword),
    (b"sample-distinct", SyntaxKind::SampleDistinctKeyword),
    (b"project-reorder", SyntaxKind::ProjectReorderKeyword),
    (b"__crossCluster", SyntaxKind::__CrossClusterKeyword),
    (b"__noWithSource", SyntaxKind::__NoWithSourceKeyword),
    (b"__packedColumn", SyntaxKind::__PackedColumnKeyword),
    (b"rowstorepolicy", SyntaxKind::RowstorePolicyKeyword),
    (b"encodingpolicy", SyntaxKind::EncodingPolicyKeyword),
    (b"graph-to-table", SyntaxKind::GraphToTableKeyword),
    (b"nooptimization", SyntaxKind::NoOptimizationKeyword),
    (b"partitioned-by", SyntaxKind::PartitionedByKeyword),
    (b"project-rename", SyntaxKind::ProjectRenameKeyword),
    (b"with_itemindex", SyntaxKind::WithItemIndexKeyword),
    (b"with_step_name", SyntaxKind::WithStepNameKeyword),
    (b"!startswith_cs", SyntaxKind::NotStartsWithCsKeyword),
    (b"set-or-replace", SyntaxKind::SetOrReplaceKeyword),
    (b"assert-schema", SyntaxKind::AssertSchemaKeyword),
    (b"cachingpolicy", SyntaxKind::CachingPolicyKeyword),
    (b"external_data", SyntaxKind::ExternalDataKeyword2),
    (b"hardretention", SyntaxKind::HardRetentionKeyword),
    (b"hint.strategy", SyntaxKind::HintDotStrategyKeyword),
    (b"matches regex", SyntaxKind::MatchesRegexKeyword),
    (b"notcontainscs", SyntaxKind::NotContainsCsKeyword),
    (b"!hasprefix_cs", SyntaxKind::NotHasPrefixCsKeyword),
    (b"!hassuffix_cs", SyntaxKind::NotHasSuffixCsKeyword),
    (b"__partitionby", SyntaxKind::PartitionByKeyword),
    (b"__projectAway", SyntaxKind::_ProjectAwayKeyword),
    (b"project-smart", SyntaxKind::ProjectSmartKeyword),
    (b"query_results", SyntaxKind::QueryResultsKeyword),
    (b"set-or-append", SyntaxKind::SetOrAppendKeyword),
    (b"softretention", SyntaxKind::SoftRetentionKeyword),
    (b"startswith_cs", SyntaxKind::StartsWithCsKeyword),
    (b"writeaheadlog", SyntaxKind::WriteAheadLogKeyword),
    (b"with_match_id", SyntaxKind::WithMatchIdKeyword),
    (b"anomalychart", SyntaxKind::AnomalyChartKeyword),
    (b"bagexpansion", SyntaxKind::BagExpansionKeyword),
    (b"decodeblocks", SyntaxKind::DecodeBlocksKeyword),
    (b"entity_group", SyntaxKind::EntityGroupKeyword),
    (b"externaldata", SyntaxKind::ExternalDataKeyword),
    (b"expandoutput", SyntaxKind::ExpandOutputKeyword),
    (b"force_remote", SyntaxKind::ForceRemoteKeyword),
    (b"hasprefix_cs", SyntaxKind::HasPrefixCsKeyword),
    (b"hassuffix_cs", SyntaxKind::HasSuffixCsKeyword),
    (b"macro-expand", SyntaxKind::MacroExpandKeyword),
    (b"project-away", SyntaxKind::ProjectAwayKeyword),
    (b"scatterchart", SyntaxKind::ScatterChartKeyword),
    (b"!contains_cs", SyntaxKind::NotBangContainsCsKeyword),
    (b"!endswith_cs", SyntaxKind::NotEndsWithCsKeyword),
    (b"with_node_id", SyntaxKind::WithNodeIdKeyword),
    (b"project-keep", SyntaxKind::ProjectKeepKeyword),
    (b"columnchart", SyntaxKind::ColumnChartKeyword),
    (b"contains_cs", SyntaxKind::ContainsCsKeyword2),
    (b"endswith_cs", SyntaxKind::EndsWithCsKeyword),
    (b"granny-desc", SyntaxKind::GrannyDescKeyword),
    (b"graph-match", SyntaxKind::GraphMatchKeyword),
    (b"best_effort", SyntaxKind::BestEffortKeyword),
    (b"ladderchart", SyntaxKind::LadderChartKeyword),
    (b"make-series", SyntaxKind::MakeSeriesKeyword),
    (b"materialize", SyntaxKind::MaterializeKeyword),
    (b"notcontains", SyntaxKind::NotContainsKeyword),
    (b"!startswith", SyntaxKind::NotStartsWithKeyword),
    (b"parse-where", SyntaxKind::ParseWhereKeyword),
    (b"hint.remote", SyntaxKind::HintDotRemoteKeyword),
    (b"hint.spread", SyntaxKind::HintDotSpreadKeyword),
    (b"top-hitters", SyntaxKind::TopHittersKeyword),
    (b"with_source", SyntaxKind::WithSourceKeyword),
    (b"accumulate", SyntaxKind::AccumulateKeyword),
    (b"bin_legacy", SyntaxKind::BinLegacy),
    (b"containscs", SyntaxKind::ContainsCsKeyword),
    (b"dataexport", SyntaxKind::DataExportKeyword),
    (b"granny-asc", SyntaxKind::GrannyAscKeyword),
    (b"harddelete", SyntaxKind::HardDeleteKeyword),
    (b"!hasprefix", SyntaxKind::NotHasPrefixKeyword),
    (b"!hassuffix", SyntaxKind::NotHasSuffixKeyword),
    (b"make-graph", SyntaxKind::MakeGraphKeyword),
    (b"pathformat", SyntaxKind::PathFormatKeyword),
    (b"pivotchart", SyntaxKind::PivotChartKeyword),
    (b"softdelete", SyntaxKind::SoftDeleteKeyword),
    (b"startswith", SyntaxKind::StartsWithKeyword),
    (b"dataformat", SyntaxKind::DataFormatKeyword),
    (b"statistics", SyntaxKind::StatisticsKeyword),
    (b"tablepurge", SyntaxKind::TablePurgeKeyword),
    (b"top-nested", SyntaxKind::TopNestedKeyword),
    (b"withsource", SyntaxKind::WithSourceKeyword2),
    (b"__crossDB", SyntaxKind::__CrossDBKeyword),
    (b"__isFuzzy", SyntaxKind::__IsFuzzyKeyword),
    (b"areachart", SyntaxKind::AreaChartKeyword),
    (b"datascope", SyntaxKind::DataScopeKeyword),
    (b"datatable", SyntaxKind::DataTableKeyword),
    (b"getschema", SyntaxKind::GetSchemaKeyword),
    (b"hasprefix", SyntaxKind::HasPrefixKeyword),
    (b"hassuffix", SyntaxKind::HasSuffixKeyword),
    (b"linechart", SyntaxKind::LineChartKeyword),
    (b"mv-expand", SyntaxKind::MvDashExpandKeyword),
    (b"notlikecs", SyntaxKind::NotLikeCsKeyword),
    (b"partition", SyntaxKind::PartitionKeyword),
    (b"rowstores", SyntaxKind::RowstoresKeyword),
    (b"serialize", SyntaxKind::SerializeKeyword),
    (b"summarize", SyntaxKind::SummarizeKeyword),
    (b"timechart", SyntaxKind::TimeChartKeyword),
    (b"timepivot", SyntaxKind::TimePivotKeyword),
    (b"!contains", SyntaxKind::NotBangContainsKeyword),
    (b"!endswith", SyntaxKind::NotEndsWithKeyword),
    (b"barchart", SyntaxKind::BarChartKeyword),
    (b"contains", SyntaxKind::ContainsKeyword),
    (b"database", SyntaxKind::DatabaseKeyword),
    (b"distinct", SyntaxKind::DistinctKeyword),
    (b"earliest", SyntaxKind::EarliestKeyword),
    (b"endswith", SyntaxKind::EndsWithKeyword),
    (b"evaluate", SyntaxKind::EvaluateKeyword),
    (b"hotcache", SyntaxKind::HotCacheKeyword),
    (b"mv-apply", SyntaxKind::MvDashApplyKeyword),
    (b"mvexpand", SyntaxKind::MvExpandKeyword),
    (b"parse-kv", SyntaxKind::ParseKvKeyword),
    (b"piechart", SyntaxKind::PieChartKeyword),
    (b"restrict", SyntaxKind::RestrictKeyword),
    (b"rowstore", SyntaxKind::RowstoreKeyword),
    (b"timeline", SyntaxKind::TimelineKeyword),
    (b"toscalar", SyntaxKind::ToScalarKeyword),
    (b"datetime", SyntaxKind::DateTimeKeyword),
    (b"timespan", SyntaxKind::TimespanKeyword),
    (b"uniqueid", SyntaxKind::UniqueIdKeyword),
    (b"3Dchart", SyntaxKind::_3DChartKeyword),
    (b"between", SyntaxKind::BetweenKeyword),
    (b"callout", SyntaxKind::CalloutKeyword),
    (b"consume", SyntaxKind::ConsumeKeyword),
    (b"declare", SyntaxKind::DeclareKeyword),
    (b"default", SyntaxKind::DefaultKeyword),
    (b"has_any", SyntaxKind::HasAnyKeyword),
    (b"has_all", SyntaxKind::HasAllKeyword),
    (b"isfuzzy", SyntaxKind::IsFuzzyKeyword),
    (b"journal", SyntaxKind::JournalKeyword),
    (b"missing", SyntaxKind::MissingKeyword),
    (b"mvapply", SyntaxKind::MvApplyKeyword),
    (b"notlike", SyntaxKind::NotLikeKeyword),
    (b"pattern", SyntaxKind::PatternKeyword),
    (b"project", SyntaxKind::ProjectKeyword),
    (b"queries", SyntaxKind::QueriesKeyword),
    (b"relaxed", SyntaxKind::RelaxedKeyword),
    (b"totable", SyntaxKind::ToTableKeyword),
    (b"treemap", SyntaxKind::TreeMapKeyword),
    (b"boolean", SyntaxKind::BooleanKeyword),
    (b"decimal", SyntaxKind::DecimalKeyword),
    (b"dynamic", SyntaxKind::DynamicKeyword),
    (b"verbose", SyntaxKind::VerboseKeyword),
    (b"plotly", SyntaxKind::PlotlyKeyword),
    (b"access", SyntaxKind::AccessKeyword),
    (b"cancel", SyntaxKind::CancelKeyword),
    (b"cycles", SyntaxKind::CyclesKeyword),
    (b"extend", SyntaxKind::ExtendKeyword),
    (b"filter", SyntaxKind::FilterKeyword),
    (b"has_cs", SyntaxKind::HasCsKeyword),
    (b"invoke", SyntaxKind::InvokeKeyword),
    (b"latest", SyntaxKind::LatestKeyword),
    (b"likecs", SyntaxKind::LikeCsKeyword),
    (b"lookup", SyntaxKind::LookupKeyword),
    (b"others", SyntaxKind::OthersKeyword),
    (b"output", SyntaxKind::OutputKeyword),
    (b"reduce", SyntaxKind::ReduceKeyword),
    (b"render", SyntaxKind::RenderKeyword),
    (b"sample", SyntaxKind::SampleKeyword),
    (b"search", SyntaxKind::SearchKeyword),
    (b"shards", SyntaxKind::ShardsKeyword),
    (b"simple", SyntaxKind::SimpleKeyword),
    (b"typeof", SyntaxKind::TypeOfKeyword),
    (b"double", SyntaxKind::DoubleKeyword),
    (b"string", SyntaxKind::StringKeyword),
    (b"uint16", SyntaxKind::UInt16Keyword),
    (b"uint32", SyntaxKind::UInt32Keyword),
    (b"uint64", SyntaxKind::UInt64Keyword),
    (b"alias", SyntaxKind::AliasKeyword),
    (b"count", SyntaxKind::CountKeyword),
    (b"edges", SyntaxKind::GraphEdgesKeyword),
    (b"facet", SyntaxKind::FacetKeyword),
    (b"first", SyntaxKind::FirstKeyword),
    (b"flags", SyntaxKind::FlagsKeyword),
    (b"graph", SyntaxKind::GraphKeyword),
    (b"limit", SyntaxKind::LimitKeyword),
    (b"nodes", SyntaxKind::NodesKeyword),
    (b"nulls", SyntaxKind::NullsKeyword),
    (b"order", SyntaxKind::OrderKeyword),
    (b"parse", SyntaxKind::ParseKeyword),
    (b"range", SyntaxKind::RangeKeyword),
    (b"regex", SyntaxKind::RegexKeyword),
    (b"seals", SyntaxKind::SealsKeyword),
    (b"title", SyntaxKind::TitleKeyword),
    (b"union", SyntaxKind::UnionKeyword),
    (b"views", SyntaxKind::ViewsKeyword),
    (b"where", SyntaxKind::WhereKeyword),
    (b"float", SyntaxKind::FloatKeyword),
    (b"int16", SyntaxKind::Int16Keyword),
    (b"int32", SyntaxKind::Int32Keyword),
    (b"int64", SyntaxKind::Int64Keyword),
    (b"uint8", SyntaxKind::UInt8Keyword),
    (b"ulong", SyntaxKind::ULongKeyword),
    (b"card", SyntaxKind::CardKeyword),
    (b"desc", SyntaxKind::DescKeyword),
    (b"find", SyntaxKind::FindKeyword),
    (b"fork", SyntaxKind::ForkKeyword),
    (b"from", SyntaxKind::FromKeyword),
    (b"join", SyntaxKind::JoinKeyword),
    (b"kind", SyntaxKind::KindKeyword),
    (b"last", SyntaxKind::LastKeyword),
    (b"like", SyntaxKind::LikeKeyword),
    (b"null", SyntaxKind::NullKeyword),
    (b"pack", SyntaxKind::PackKeyword),
    (b"scan", SyntaxKind::ScanKeyword),
    (b"sort", SyntaxKind::SortKeyword),
    (b"step", SyntaxKind::StepKeyword),
    (b"take", SyntaxKind::TakeKeyword),
    (b"view", SyntaxKind::ViewKeyword),
    (b"bool", SyntaxKind::BoolKeyword),
    (b"byte", SyntaxKind::ByteKeyword),
    (b"char", SyntaxKind::CharKeyword),
    (b"date", SyntaxKind::DateKeyword),
    (b"guid", SyntaxKind::GuidKeyword),
    (b"int8", SyntaxKind::Int8Keyword),
    (b"long", SyntaxKind::LongKeyword),
    (b"real", SyntaxKind::RealKeyword),
    (b"time", SyntaxKind::TimeKeyword),
    (b"uint", SyntaxKind::UIntKeyword),
    (b"!has", SyntaxKind::NotHasKeyword),
    (b"!in~", SyntaxKind::NotInCsKeyword),
    (b"seal", SyntaxKind::SealKeyword),
    (b"__id", SyntaxKind::__IdKeyword),
    (b"and", SyntaxKind::AndKeyword),
    (b"asc", SyntaxKind::AscKeyword),
    (b"bin", SyntaxKind::BinKeyword),
    (b"has", SyntaxKind::HasKeyword),
    (b"in~", SyntaxKind::InCsKeyword),
    (b"let", SyntaxKind::LetKeyword),
    (b"mdm", SyntaxKind::MdmKeyword),
    (b"set", SyntaxKind::SetKeyword),
    (b"sql", SyntaxKind::SqlKeyword),
    (b"top", SyntaxKind::TopKeyword),
    (b"int", SyntaxKind::IntKeyword),
    (b"!in", SyntaxKind::NotInKeyword),
    (b"as", SyntaxKind::AsKeyword),
    (b"by", SyntaxKind::ByKeyword),
    (b"id", SyntaxKind::IdKeyword),
    (b"in", SyntaxKind::InKeyword),
    (b"of", SyntaxKind::OfKeyword),
    (b"on", SyntaxKind::OnKeyword),
    (b"or", SyntaxKind::OrKeyword),
    (b"to", SyntaxKind::ToKeyword),
];
