use super::TokenKind;

pub(crate) const UTF8_1_BYTE_MASK: u8 = 0b1000_0000;
pub(crate) const UTF8_1_BYTE_PATTERN: u8 = 0b0000_0000;
pub(crate) const UTF8_2_BYTE_MASK: u8 = 0b1110_0000;
pub(crate) const UTF8_2_BYTE_PATTERN: u8 = 0b1100_0000;
pub(crate) const UTF8_3_BYTE_MASK: u8 = 0b1111_0000;
pub(crate) const UTF8_3_BYTE_PATTERN: u8 = 0b1110_0000;
pub(crate) const UTF8_4_BYTE_MASK: u8 = 0b1111_1000;
pub(crate) const UTF8_4_BYTE_PATTERN: u8 = 0b1111_0000;
pub(crate) const AVG_BYTES_PER_TOKEN: usize = 5;
pub(crate) const MULTI_LINE_STRING_SEQUENCES: &[&[u8]] = &[b"```", b"~~~"];
pub(crate) const BOOL_LITERALS: &[&[u8]] =
    &[b"true", b"false", b"True", b"False", b"TRUE", b"FALSE"];
pub(crate) const TIMESPAN_SUFFIXES: &[&[u8]] = &[
    b"microseconds",
    b"milliseconds",
    b"nanoseconds",
    b"microsecond",
    b"millisecond",
    b"nanosecond",
    b"microsec",
    b"millisec",
    b"nanosec",
    b"minutes",
    b"seconds",
    b"hours",
    b"micros",
    b"millis",
    b"nanos",
    b"minute",
    b"second",
    b"hour",
    b"micro",
    b"milli",
    b"nano",
    b"ticks",
    b"tick",
    b"hrs",
    b"sec",
    b"min",
    b"day",
    b"ms",
    b"hr",
    b"d",
    b"h",
    b"m",
    b"s",
];
pub(crate) const KEYWORDS: &[(&[u8], TokenKind)] = &[
    (
        b"storedqueryresultcontainers",
        TokenKind::StoredQueryResultContainersKeyword,
    ),
    (
        b"materialized-view-combine",
        TokenKind::MaterializedViewCombineKeyword,
    ),
    (
        b"__contextual_datatable",
        TokenKind::ContextualDataTableKeyword,
    ),
    (
        b"restricted_view_access",
        TokenKind::RestrictedViewAccessKeyword,
    ),
    (
        b"extent_tags_retention",
        TokenKind::ExtentTagsRetentionKeyword,
    ),
    (
        b"inline_external_table",
        TokenKind::InlineExternalTableKeyword,
    ),
    (
        b"graph-mark-components",
        TokenKind::GraphMarkComponentsKeyword,
    ),
    (
        b"commands-and-queries",
        TokenKind::CommandsAndQueriesKeyword,
    ),
    (
        b"graph-shortest-paths",
        TokenKind::GraphShortestPathsKeyword,
    ),
    (
        b"hint.progressive_top",
        TokenKind::HintDotProgressiveTopKeyword,
    ),
    (
        b"__sourceColumnIndex",
        TokenKind::__SourceColumnIndexKeyword,
    ),
    (b"hint.num_partitions", TokenKind::HintDotNumPartitions),
    (b"rowstore_references", TokenKind::RowstoreReferencesKeyword),
    (
        b"unrestrictedviewers",
        TokenKind::UnrestrictedViewersKeyword,
    ),
    (b"materialized-views", TokenKind::MaterializedViewsKeyword),
    (b"row_level_security", TokenKind::RowLevelSecurityKeyword),
    (b"__executeAndCache", TokenKind::ExecuteAndCacheKeyword),
    (b"hint.distribution", TokenKind::HintDotDistributionKeyword),
    (b"hint.materialized", TokenKind::HintDotMaterializedKeyword),
    (b"graph-where-nodes", TokenKind::GraphWhereNodesKeyword),
    (b"graph-where-edges", TokenKind::GraphWhereEdgesKeyword),
    (b"rowstore_sealinfo", TokenKind::RowstoreSealInfoKeyword),
    (b"datetime_pattern", TokenKind::DateTimePatternKeyword),
    (b"project-by-names", TokenKind::ProjectByNamesKeyword),
    (b"query_parameters", TokenKind::QueryParametersKeyword),
    (b"stackedareachart", TokenKind::StackedAreaChartKeyword),
    (b"hint.concurrency", TokenKind::HintDotConcurrencyKeyword),
    (b"hint.shufflekey", TokenKind::HintDotShuffleKeyKeyword),
    (b"sample-distinct", TokenKind::SampleDistinctKeyword),
    (b"project-reorder", TokenKind::ProjectReorderKeyword),
    (b"__crossCluster", TokenKind::__CrossClusterKeyword),
    (b"__noWithSource", TokenKind::__NoWithSourceKeyword),
    (b"__packedColumn", TokenKind::__PackedColumnKeyword),
    (b"rowstorepolicy", TokenKind::RowstorePolicyKeyword),
    (b"encodingpolicy", TokenKind::EncodingPolicyKeyword),
    (b"graph-to-table", TokenKind::GraphToTableKeyword),
    (b"nooptimization", TokenKind::NoOptimizationKeyword),
    (b"partitioned-by", TokenKind::PartitionedByKeyword),
    (b"project-rename", TokenKind::ProjectRenameKeyword),
    (b"with_itemindex", TokenKind::WithItemIndexKeyword),
    (b"with_step_name", TokenKind::WithStepNameKeyword),
    (b"!startswith_cs", TokenKind::NotStartsWithCsKeyword),
    (b"set-or-replace", TokenKind::SetOrReplaceKeyword),
    (b"assert-schema", TokenKind::AssertSchemaKeyword),
    (b"cachingpolicy", TokenKind::CachingPolicyKeyword),
    (b"external_data", TokenKind::ExternalDataKeyword2),
    (b"hardretention", TokenKind::HardRetentionKeyword),
    (b"hint.strategy", TokenKind::HintDotStrategyKeyword),
    (b"matches regex", TokenKind::MatchesRegexKeyword),
    (b"notcontainscs", TokenKind::NotContainsCsKeyword),
    (b"!hasprefix_cs", TokenKind::NotHasPrefixCsKeyword),
    (b"!hassuffix_cs", TokenKind::NotHasSuffixCsKeyword),
    (b"__partitionby", TokenKind::PartitionByKeyword),
    (b"__projectAway", TokenKind::_ProjectAwayKeyword),
    (b"project-smart", TokenKind::ProjectSmartKeyword),
    (b"query_results", TokenKind::QueryResultsKeyword),
    (b"set-or-append", TokenKind::SetOrAppendKeyword),
    (b"softretention", TokenKind::SoftRetentionKeyword),
    (b"startswith_cs", TokenKind::StartsWithCsKeyword),
    (b"writeaheadlog", TokenKind::WriteAheadLogKeyword),
    (b"with_match_id", TokenKind::WithMatchIdKeyword),
    (b"anomalychart", TokenKind::AnomalyChartKeyword),
    (b"bagexpansion", TokenKind::BagExpansionKeyword),
    (b"decodeblocks", TokenKind::DecodeBlocksKeyword),
    (b"entity_group", TokenKind::EntityGroupKeyword),
    (b"externaldata", TokenKind::ExternalDataKeyword),
    (b"expandoutput", TokenKind::ExpandOutputKeyword),
    (b"force_remote", TokenKind::ForceRemoteKeyword),
    (b"hasprefix_cs", TokenKind::HasPrefixCsKeyword),
    (b"hassuffix_cs", TokenKind::HasSuffixCsKeyword),
    (b"macro-expand", TokenKind::MacroExpandKeyword),
    (b"project-away", TokenKind::ProjectAwayKeyword),
    (b"scatterchart", TokenKind::ScatterChartKeyword),
    (b"!contains_cs", TokenKind::NotBangContainsCsKeyword),
    (b"!endswith_cs", TokenKind::NotEndsWithCsKeyword),
    (b"with_node_id", TokenKind::WithNodeIdKeyword),
    (b"project-keep", TokenKind::ProjectKeepKeyword),
    (b"columnchart", TokenKind::ColumnChartKeyword),
    (b"contains_cs", TokenKind::ContainsCsKeyword2),
    (b"endswith_cs", TokenKind::EndsWithCsKeyword),
    (b"granny-desc", TokenKind::GrannyDescKeyword),
    (b"graph-match", TokenKind::GraphMatchKeyword),
    (b"best_effort", TokenKind::BestEffortKeyword),
    (b"ladderchart", TokenKind::LadderChartKeyword),
    (b"make-series", TokenKind::MakeSeriesKeyword),
    (b"materialize", TokenKind::MaterializeKeyword),
    (b"notcontains", TokenKind::NotContainsKeyword),
    (b"!startswith", TokenKind::NotStartsWithKeyword),
    (b"parse-where", TokenKind::ParseWhereKeyword),
    (b"hint.remote", TokenKind::HintDotRemoteKeyword),
    (b"hint.spread", TokenKind::HintDotSpreadKeyword),
    (b"top-hitters", TokenKind::TopHittersKeyword),
    (b"with_source", TokenKind::WithSourceKeyword),
    (b"accumulate", TokenKind::AccumulateKeyword),
    (b"bin_legacy", TokenKind::BinLegacy),
    (b"containscs", TokenKind::ContainsCsKeyword),
    (b"dataexport", TokenKind::DataExportKeyword),
    (b"granny-asc", TokenKind::GrannyAscKeyword),
    (b"harddelete", TokenKind::HardDeleteKeyword),
    (b"!hasprefix", TokenKind::NotHasPrefixKeyword),
    (b"!hassuffix", TokenKind::NotHasSuffixKeyword),
    (b"make-graph", TokenKind::MakeGraphKeyword),
    (b"pathformat", TokenKind::PathFormatKeyword),
    (b"pivotchart", TokenKind::PivotChartKeyword),
    (b"softdelete", TokenKind::SoftDeleteKeyword),
    (b"startswith", TokenKind::StartsWithKeyword),
    (b"dataformat", TokenKind::DataFormatKeyword),
    (b"statistics", TokenKind::StatisticsKeyword),
    (b"tablepurge", TokenKind::TablePurgeKeyword),
    (b"top-nested", TokenKind::TopNestedKeyword),
    (b"withsource", TokenKind::WithSourceKeyword2),
    (b"__crossDB", TokenKind::__CrossDBKeyword),
    (b"__isFuzzy", TokenKind::__IsFuzzyKeyword),
    (b"areachart", TokenKind::AreaChartKeyword),
    (b"datascope", TokenKind::DataScopeKeyword),
    (b"datatable", TokenKind::DataTableKeyword),
    (b"getschema", TokenKind::GetSchemaKeyword),
    (b"hasprefix", TokenKind::HasPrefixKeyword),
    (b"hassuffix", TokenKind::HasSuffixKeyword),
    (b"linechart", TokenKind::LineChartKeyword),
    (b"mv-expand", TokenKind::MvDashExpandKeyword),
    (b"notlikecs", TokenKind::NotLikeCsKeyword),
    (b"partition", TokenKind::PartitionKeyword),
    (b"rowstores", TokenKind::RowstoresKeyword),
    (b"serialize", TokenKind::SerializeKeyword),
    (b"summarize", TokenKind::SummarizeKeyword),
    (b"timechart", TokenKind::TimeChartKeyword),
    (b"timepivot", TokenKind::TimePivotKeyword),
    (b"!contains", TokenKind::NotBangContainsKeyword),
    (b"!endswith", TokenKind::NotEndsWithKeyword),
    (b"barchart", TokenKind::BarChartKeyword),
    (b"contains", TokenKind::ContainsKeyword),
    (b"database", TokenKind::DatabaseKeyword),
    (b"distinct", TokenKind::DistinctKeyword),
    (b"earliest", TokenKind::EarliestKeyword),
    (b"endswith", TokenKind::EndsWithKeyword),
    (b"evaluate", TokenKind::EvaluateKeyword),
    (b"hotcache", TokenKind::HotCacheKeyword),
    (b"mv-apply", TokenKind::MvDashApplyKeyword),
    (b"mvexpand", TokenKind::MvExpandKeyword),
    (b"parse-kv", TokenKind::ParseKvKeyword),
    (b"piechart", TokenKind::PieChartKeyword),
    (b"restrict", TokenKind::RestrictKeyword),
    (b"rowstore", TokenKind::RowstoreKeyword),
    (b"timeline", TokenKind::TimelineKeyword),
    (b"toscalar", TokenKind::ToScalarKeyword),
    (b"datetime", TokenKind::DateTimeKeyword),
    (b"timespan", TokenKind::TimespanKeyword),
    (b"uniqueid", TokenKind::UniqueIdKeyword),
    (b"3Dchart", TokenKind::_3DChartKeyword),
    (b"between", TokenKind::BetweenKeyword),
    (b"callout", TokenKind::CalloutKeyword),
    (b"consume", TokenKind::ConsumeKeyword),
    (b"declare", TokenKind::DeclareKeyword),
    (b"default", TokenKind::DefaultKeyword),
    (b"has_any", TokenKind::HasAnyKeyword),
    (b"has_all", TokenKind::HasAllKeyword),
    (b"isfuzzy", TokenKind::IsFuzzyKeyword),
    (b"journal", TokenKind::JournalKeyword),
    (b"missing", TokenKind::MissingKeyword),
    (b"mvapply", TokenKind::MvApplyKeyword),
    (b"notlike", TokenKind::NotLikeKeyword),
    (b"pattern", TokenKind::PatternKeyword),
    (b"project", TokenKind::ProjectKeyword),
    (b"queries", TokenKind::QueriesKeyword),
    (b"relaxed", TokenKind::RelaxedKeyword),
    (b"totable", TokenKind::ToTableKeyword),
    (b"treemap", TokenKind::TreeMapKeyword),
    (b"boolean", TokenKind::BooleanKeyword),
    (b"decimal", TokenKind::DecimalKeyword),
    (b"dynamic", TokenKind::DynamicKeyword),
    (b"verbose", TokenKind::VerboseKeyword),
    (b"plotly", TokenKind::PlotlyKeyword),
    (b"access", TokenKind::AccessKeyword),
    (b"cancel", TokenKind::CancelKeyword),
    (b"cycles", TokenKind::CyclesKeyword),
    (b"extend", TokenKind::ExtendKeyword),
    (b"filter", TokenKind::FilterKeyword),
    (b"has_cs", TokenKind::HasCsKeyword),
    (b"invoke", TokenKind::InvokeKeyword),
    (b"latest", TokenKind::LatestKeyword),
    (b"likecs", TokenKind::LikeCsKeyword),
    (b"lookup", TokenKind::LookupKeyword),
    (b"others", TokenKind::OthersKeyword),
    (b"output", TokenKind::OutputKeyword),
    (b"reduce", TokenKind::ReduceKeyword),
    (b"render", TokenKind::RenderKeyword),
    (b"sample", TokenKind::SampleKeyword),
    (b"search", TokenKind::SearchKeyword),
    (b"shards", TokenKind::ShardsKeyword),
    (b"simple", TokenKind::SimpleKeyword),
    (b"typeof", TokenKind::TypeOfKeyword),
    (b"double", TokenKind::DoubleKeyword),
    (b"string", TokenKind::StringKeyword),
    (b"uint16", TokenKind::UInt16Keyword),
    (b"uint32", TokenKind::UInt32Keyword),
    (b"uint64", TokenKind::UInt64Keyword),
    (b"alias", TokenKind::AliasKeyword),
    (b"count", TokenKind::CountKeyword),
    (b"edges", TokenKind::GraphEdgesKeyword),
    (b"facet", TokenKind::FacetKeyword),
    (b"first", TokenKind::FirstKeyword),
    (b"flags", TokenKind::FlagsKeyword),
    (b"graph", TokenKind::GraphKeyword),
    (b"limit", TokenKind::LimitKeyword),
    (b"nodes", TokenKind::NodesKeyword),
    (b"nulls", TokenKind::NullsKeyword),
    (b"order", TokenKind::OrderKeyword),
    (b"parse", TokenKind::ParseKeyword),
    (b"range", TokenKind::RangeKeyword),
    (b"regex", TokenKind::RegexKeyword),
    (b"seals", TokenKind::SealsKeyword),
    (b"title", TokenKind::TitleKeyword),
    (b"union", TokenKind::UnionKeyword),
    (b"views", TokenKind::ViewsKeyword),
    (b"where", TokenKind::WhereKeyword),
    (b"float", TokenKind::FloatKeyword),
    (b"int16", TokenKind::Int16Keyword),
    (b"int32", TokenKind::Int32Keyword),
    (b"int64", TokenKind::Int64Keyword),
    (b"uint8", TokenKind::UInt8Keyword),
    (b"ulong", TokenKind::ULongKeyword),
    (b"card", TokenKind::CardKeyword),
    (b"desc", TokenKind::DescKeyword),
    (b"find", TokenKind::FindKeyword),
    (b"fork", TokenKind::ForkKeyword),
    (b"from", TokenKind::FromKeyword),
    (b"join", TokenKind::JoinKeyword),
    (b"kind", TokenKind::KindKeyword),
    (b"last", TokenKind::LastKeyword),
    (b"like", TokenKind::LikeKeyword),
    (b"null", TokenKind::NullKeyword),
    (b"pack", TokenKind::PackKeyword),
    (b"scan", TokenKind::ScanKeyword),
    (b"sort", TokenKind::SortKeyword),
    (b"step", TokenKind::StepKeyword),
    (b"take", TokenKind::TakeKeyword),
    (b"view", TokenKind::ViewKeyword),
    (b"bool", TokenKind::BoolKeyword),
    (b"byte", TokenKind::ByteKeyword),
    (b"char", TokenKind::CharKeyword),
    (b"date", TokenKind::DateKeyword),
    (b"guid", TokenKind::GuidKeyword),
    (b"int8", TokenKind::Int8Keyword),
    (b"long", TokenKind::LongKeyword),
    (b"real", TokenKind::RealKeyword),
    (b"time", TokenKind::TimeKeyword),
    (b"uint", TokenKind::UIntKeyword),
    (b"!has", TokenKind::NotHasKeyword),
    (b"!in~", TokenKind::NotInCsKeyword),
    (b"seal", TokenKind::SealKeyword),
    (b"__id", TokenKind::__IdKeyword),
    (b"and", TokenKind::AndKeyword),
    (b"asc", TokenKind::AscKeyword),
    (b"bin", TokenKind::BinKeyword),
    (b"has", TokenKind::HasKeyword),
    (b"in~", TokenKind::InCsKeyword),
    (b"let", TokenKind::LetKeyword),
    (b"mdm", TokenKind::MdmKeyword),
    (b"set", TokenKind::SetKeyword),
    (b"sql", TokenKind::SqlKeyword),
    (b"top", TokenKind::TopKeyword),
    (b"int", TokenKind::IntKeyword),
    (b"!in", TokenKind::NotInKeyword),
    (b"as", TokenKind::AsKeyword),
    (b"by", TokenKind::ByKeyword),
    (b"id", TokenKind::IdKeyword),
    (b"in", TokenKind::InKeyword),
    (b"of", TokenKind::OfKeyword),
    (b"on", TokenKind::OnKeyword),
    (b"or", TokenKind::OrKeyword),
    (b"to", TokenKind::ToKeyword),
];
